### ISSUE TITLE
Capstone - SQL - Cool T-Shirts

### ISSUE THREAD

**Issue by cviddy17** [sgm-holly/sql-scratch-capstone-turn-in#1]
### Criteria 1: Report: Are conclusions clear and supported by evidence in all eight answers?
* _Score Level:_ 4/4 Exceeds Expectations
* _Comment(s):_ All of the questions were thoroughly answered through not only the responses from the queries, but also with insight and analysis. Great job!
 
### Criteria 2: Query Accuracy: Do queries do what they were supposed to do?
* _Score Level:_ 4/4 Exceeds Expectations
* _Comment(s):_ All queries produced accurate and thorough output.
 
### Criteria 3: Query Formatting
* _Score Level:_ 4/4 Exceeds Expectations
* _Comment(s):_ Queries adhere to the style guide and were properly commented and separated along the way as well.
 
### Criteria 4: Understanding underlying concepts and terminology
* _Score Level:_ 4/4 Exceeds Expectations
* _Comment(s):_ Insights derived from query analysis were excellent and thorough - there is a proven deep understanding of first and last touches and how they would affect overall sales.

 ### Overall Score: 16/16
Your presentation was stellar - you showed not only the charts and results from each query, but also the underlying code and an explanation and analysis, as well as using a web-safe font that ties everything together and makes the presentation stand out among others. You have a great command of SQL, and we hope you have enjoyed this course.

**Comment by sgm-holly** [comment]
Thank you so much! 😊
